### ISSUE TITLE
graphics_toolkit: gnuplot toolkit is not available

### ISSUE THREAD

**Issue by AetherLorde** [blink1073/oct2py#116]
I have seeing weird behavior on most Octave functions called from the Oct2Py object. Even just calling the ones function produces the following error. 

error: graphics_toolkit: gnuplot toolkit is not available
error: called from graphics_toolkit at line 81 column 5

The function is still running and returning fine to the python code, it just also throws/shows the above  octave error. It seems that this does not always occur on the first run of a function. 

Thanks again for this project!

**Comment by blink1073** [comment]
Hi @AetherLorde, can you please try `pip install -U octave_kernel`?  `oct2py` uses the the `octave_kernel` for low level interaction, and I made a release of `octave_kernel` that should fix the problem.

**Comment by AetherLorde** [comment]
It tells me the requirement is already met. I also did pip install -U oct2py. The error persists

**Comment by blink1073** [comment]
What is the output of `pip list | grep octave-kernel`?

**Comment by AetherLorde** [comment]
So it looks like my octave_kernel isn't installed via pip, but instead via conda. It looks like the conda version and the pip version are both at .26.

**Comment by blink1073** [comment]
octave_kernel 0.26.1 is now available on pip (conda pending).  It now checks to see if gnuplot is available before setting it as the `graphics_toolkit`.

**Comment by AetherLorde** [comment]
Still seeing this unfortunately with 

oct2py                    4.0.4                     <pip>
octave-kernel             0.26.2                    <pip>

I also tried installing version .26.1 specifically and the error was still present unfortunately.

**Comment by blink1073** [comment]
What is the output of `available_graphics_toolkits` in Octave?

**Comment by AetherLorde** [comment]
octave:1> available_graphics_toolkits
ans = 
{
  [1,1] = fltk
}

**Comment by blink1073** [comment]
If you install 0.26.1 specifically, does it print `gnuplot` to the terminal?

**Comment by AetherLorde** [comment]
No, still just 

```
octave:1> available_graphics_toolkits
ans = 
{
  [1,1] = fltk
}
```

**Comment by blink1073** [comment]
Sorry, I mean in the terminal when you run the notebook: https://github.com/Calysto/octave_kernel/commit/39025eedc7dde19fbc39ad3921214e4c2b852b01#diff-7aa6445107b53b67eaeceb6838b981dcR283.

**Comment by AetherLorde** [comment]
So I started an ipython repl, imported octave_kernel.kernel and then made an OctaveEngine. ```gnuplot``` was not printed to the screen at any point. Are there other steps that I should try? I actually am not running any of this via a full notebook if that makes a difference

**Comment by blink1073** [comment]
What sequence of actions gives you the gnuplot error now?

**Comment by AetherLorde** [comment]
I still see it on function calls through oct2py after the first. So if I import oct2py, instantiate an Oct2Py object, and then start making calls, even just to ones and zeros functions, it will start displaying the error from the second call onward.

**Comment by blink1073** [comment]
Ah, whoops, didn't see that we were also explicitly setting `gnuplot` in `oct2py`.  Fixed 01b85951c6c5cd4f6e9c580a8d8e1584f17399e6, released as 4.0.5.

**Comment by AetherLorde** [comment]
Updated this morning and its working! Thanks!

**Comment by blink1073** [comment]
Great!  Thanks for your persistence!

**Comment by blink1073** [comment]
Ha, I meant perseverance, not persistence.
