### ISSUE TITLE
Oct2py AttributeError: 'module' object has no attribute 'getgroups'

### ISSUE THREAD

**Issue by toast216** [blink1073/oct2py#85]
Might be a stupid question with a really simple answer. I have set the exec path and opening cmd and typing octave opens up octave. But when running in python I get the error AttributeError: 'module' object has no attribute 'getgroups'.

Python 2.7
Octave 4.0.0

**Comment by blink1073** [comment]
Hi @toast216, can you print the code and full traceback?

**Comment by toast216** [comment]
File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Raph/Documents/Python Scripts/Reading In Raster/read_raster_v1.py", line 9, in <module>
    import oct2py

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\__init__.py", line 69, in <module>
    octave = Oct2Py()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 86, in __init__
    self.restart()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 391, in restart
    self._session = _Session(self._executable, self.logger)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 643, in __init__
    self.proc = self.start(executable)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 693, in start
    if not executable or not which(executable):

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 189, in which
    if os.path.dirname(filename) != '' and is_executable_file(filename):

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 168, in is_executable_file
    user_gids = os.getgroups() + [os.getgid()]

AttributeError: 'module' object has no attribute 'getgroups'

**Comment by blink1073** [comment]
Yep, that is a bug, looks like `os.getgroups` is Unix only.  I'll fix it tonight.

**Comment by toast216** [comment]
Awesome! Thanks! I was going crazy trying to find out what was wrong!

**Comment by toast216** [comment]
Quick question: How was everyone else able to run python + oct2py + windows before this? Because it seems like it generated in the import?

**Comment by blink1073** [comment]
I had recently added that part of the code, and must not have tested it well enough on Windows (I use OSX).  I released 3.5.1 with a fix.

**Comment by toast216** [comment]
Upgraded to 3.5.1 this morning. Still the same error just a little different output:


  File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Raph/Documents/Python Scripts/Reading In Raster/read_raster_v1.py", line 9, in <module>
    import oct2py

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\__init__.py", line 69, in <module>
    octave = Oct2Py()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 86, in __init__
    self.restart()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 391, in restart
    self._session = _Session(self._executable, self.logger)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 643, in __init__
    self.proc = self.start(executable)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 693, in start
    if not executable or not which(executable):

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 189, in which
    if found and executable. Otherwise this returns None.'''

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 168, in is_executable_file

AttributeError: 'module' object has no attribute 'getgroups'

**Comment by toast216** [comment]
This is Windows 7 if it helps at all

**Comment by blink1073** [comment]
What is the output of `python -c "import pty"`?

**Comment by toast216** [comment]
python -c "import pty"
File "<string>", line 1, in <module>
File "C:\Users\Raph\Anaconda2\lib\pty.py", line 11, in <module> import tty
File "C:\Users\Raph\Anaconda2\lib\tty.py", line 5, in <module> from termios import *
ImportError: No module name termios

This?

**Comment by toast216** [comment]
There are <'module'> in there too but they went away

**Comment by blink1073** [comment]
I am confused, you should never get past this line: 

https://github.com/blink1073/oct2py/blob/master/oct2py/utils.py#L147

Because of this part:
https://github.com/blink1073/oct2py/blob/master/oct2py/utils.py#L12

**Comment by blink1073** [comment]
You might try adding a `print(pty)` before line 147 to see what it is picking up.

**Comment by toast216** [comment]
returns True for print(pty)

**Comment by blink1073** [comment]
as in, it prints "True"?

**Comment by toast216** [comment]
it prints "return True"


  File "<ipython-input-15-430bdd71dca0>", line 1, in <module>
    runfile('C:/Users/Raph/Documents/Python Scripts/Reading In Raster/read_raster_v1.py', wdir='C:/Users/Raph/Documents/Python Scripts/Reading In Raster')

  File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Raph/Documents/Python Scripts/Reading In Raster/read_raster_v1.py", line 9, in <module>
    import oct2py

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\__init__.py", line 69, in <module>
    octave = Oct2Py()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 86, in __init__
    self.restart()

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 391, in restart
    self._session = _Session(self._executable, self.logger)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 643, in __init__
    self.proc = self.start(executable)

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\core.py", line 693, in start
    if not executable or not which(executable):

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 189, in which
    then checks if it is executable. This returns the full path to the filename

  File "C:\Users\Raph\Anaconda2\lib\site-packages\oct2py\utils.py", line 168, in is_executable_file
   ** return True**

AttributeError: 'module' object has no attribute 'getgroups'

**Comment by toast216** [comment]
I ended up just putting:
pty = None right before 
if not pty:
     return false

Works for now as a bandaid. No idea why it wasn't working before and I'm with you on that it should've worked.

**Comment by blink1073** [comment]
Can you change that line to `if os.name == 'nt'` and make sure it still works?  If so, I'll cut a new release.

**Comment by toast216** [comment]
Yes that change works.

Running into more problems now: 

import oct2py as op

octave = op.Oct2Py()
octave.addpath('C:/Users/Raph/Documents/Python Scripts/Reading In Raster/Lump Finder DLL')

And then python crashes on the addpath command. Python.exe has stopped working

**Comment by blink1073** [comment]
Try adding a `r''` to make it a raw path.  You've run into another Windows limitation.  Because we are not using a pseudo-tty, Octave forcibly closes the connection when there is an uncaught error.

**Comment by toast216** [comment]
Like this?
octave.addpath(r'C:/Users/Raph/Documents/Python Scripts/Reading In Raster/Lump Finder DLL/')

still crashes. Would it have anything to do with admin privileges?
And yes I'm currently hating windows. Again thanks for all this, you've been immensely helpful.

**Comment by blink1073** [comment]
does that `addpath` work from an Octave prompt?

**Comment by toast216** [comment]
Yup!

**Comment by blink1073** [comment]
can you add any other path from `oct2py`?

**Comment by toast216** [comment]
Negative.

So in regular Ipython it crashes when I hit enter on the addpath command.
In Spyder it crashes on octave.addpath(
The second I type in that first parenthesis it crashes.

Another thing is I have my octave_executable set to the cli of octave, but now when I go to cmd it says 
"octave is not recognized as an internal or external command, operable program or batch file."

**Comment by blink1073** [comment]
`OCTAVE_EXECUTABLE` is only recognized by `oct2py`.  Are you able to run any other commands, like `octave.ones(3)`?

**Comment by toast216** [comment]
Same issue the second I open a parenthesis after octave.ones it crashes in Spyder

**Comment by blink1073** [comment]
I just tried again in my Windows VM, and it works fine.  I'm not sure exactly how to proceed.  There is definitely something strange with your setup (as evidenced by the `pty` thing), but I don't know what it could be.

**Comment by toast216** [comment]
Agreed, I'm moving to linux to see if things work better.

**Comment by blink1073** [comment]
Ha, another can of worms ;)

**Comment by toast216** [comment]
Using this thread because it's still open. Using Oct2py is it possible to load packages in octave? ie. pkg load image?

Or is there another way to do it programmatically instead of typing it into the octave cli?

**Comment by blink1073** [comment]
Hi @toast216, you can use `octave.eval('pkg load signal')` to load the signal package, for example

**Comment by toast216** [comment]
sweet thanks I ended up just adding it to whatever octave call I was doing, but this is much nicer

**Comment by toast216** [comment]
Hey back again! I'm running on linux and things are working much better. We are not using any sort of gui for octave how can we supress these 2 warnings:

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features

**Comment by blink1073** [comment]
Do you have an `octave-cli` program?  If so, you can set `OCTAVE_EXECUTABLE` to point to it.

**Comment by toast216** [comment]
yup its already pointing to that and everything runs fine:
import os
os.environ['OCTAVE_EXECUTABLE']='/opt/octave-4.0.0/bin/octave'
octave gets called runs all my functions properly we just want to suppress those warnings if possible

**Comment by blink1073** [comment]
Not sure off the top of my head, I'll have a look this weekend.

**Comment by blink1073** [comment]
Hi @toast216, I believe 6fe0514f7154274076e174c6a4f4f3eaf22100e8 should fix the warning, are you able to run from a git clone?

**Comment by toast216** [comment]
I don't know how to run from a git clone but I'm sure I could figure it out.

I tried adding:
 + if 'octave-cli' not in executable:
 +            try:
 +                info = subprocess.check_output([executable, '--version'])
 +            except OSError:  # pragma: no cover
 +                raise Oct2PyError(errmsg)

And tabbing the other stuff over and commenting out the first part. Still getting warnings upon running program.

**Comment by blink1073** [comment]
Hmm, how about adding this print statement?

```diff
--- a/oct2py/core.py
+++ b/oct2py/core.py
@@ -713,7 +713,7 @@ class _Session(object):

             if 'version 4' in info.decode('utf-8').lower():
                 args += ['--no-gui']
-
+        print(args, kwargs)
         try:
             proc = subprocess.Popen(args, **kwargs)
```

**Comment by toast216** [comment]
this is what I get with that print statement:

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
['/opt/octave-4.0.0/bin/octave', '-q', '--no-gui'] {'close_fds': True, 'stdin': 5, 'bufsize': 0, 'stderr': 5, 'stdout': 5}
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
['/opt/octave-4.0.0/bin/octave', '-q', '--no-gui'] {'close_fds': True, 'stdin': 7, 'bufsize': 0, 'stderr': 7, 'stdout': 7}

**Comment by blink1073** [comment]
Do you have an `octave-cli` executable?  If so, you can set the `OCTAV_EXECUTABLE` variable to its path, and that should resolve your problem.

**Comment by toast216** [comment]
Nice! Works! I had to compile from source(since its 4.0 on a server) and I honestly didn't really know if I had installed everything correctly. Consider this closed

**Comment by blink1073** [comment]
Great!
